### ISSUE TITLE
Error in textaDetectTopics()

### ISSUE THREAD

**Issue by andreaphsz** [philferriere/mscstexta4r#1]
I called:

```
tryCatch({

  # Detect top topics
  textaDetectTopics(
    documents = documents, # At least 100 docs/sentences
    stopWords = NULL,             # Stop word list (optional)
    topicsToExclude = NULL,       # Topics to exclude (optional)
    minDocumentsPerWord = NULL,   # Threshold to exclude rare topics (optional)
    maxDocumentsPerWord = NULL,   # Threshold to exclude ubiquitous topics (optional)
    resultsPollInterval = 30L,    # Poll interval (in s, default: 30s, use 0L for async)
    resultsTimeout = 1200L,       # Give up timeout (in s, default: 1200s = 20mn)
    verbose = FALSE               # If set to TRUE, print every poll status to stdout
  )

}, error = function(err) {

  # Print error
  geterrmessage()

})
```

and got the error:

```
textatopics [https://westus.api.cognitive.microsoft.com/text/analytics/v2.0/topics?]
status: Failed
operationId: 0c0783bf1f484dc6a34b6df7198f*
operationType: topics
Fehler in if (nrow(x$topics) > 20) cat("topics (first 20):\n", sep = "") else cat("topics:\n",  : 
  Argument hat Länge 0
```

Any idea?

**Comment by philferriere** [comment]
Thank you for reporting the issue, Andrea!

The package's auto print function is trying to print a list of topics, even though the topic detection operation clearly failed (as indicated by the status message). I'll work on making the auto print function more robust (it's too naive, right now).

Meanwhile, you can try and debug why it failed by digging into the details of the servers' JSON response. If you rewrite your code as:

`myTopics<- textaDetectTopics(blah blah)`

The field `myTopics$json` will contain the details of the servers' response. Do you see any information in there that may help you understand what the problem is?

Also, `textaDetectLanguages()` tells me that `Argument hat Länge 0` is German. At this point, MS Cognitive Services' topic detection only supports English. Just to be sure -- what's the language of the documents you're trying to detect topics for?

If you still can't figure out what the issue is afterwards, can you provide a small input sample that triggers the problem (100 short sentences)?

**Comment by philferriere** [comment]
I made the auto print function a bit more robust. Do you mind installing the development version, Andrea, and confirm that, even though topic detection is failing, at least the print operation doesn't generate an error?

```
remove.packages("mscstexta4r")
if ("devtools" %in% installed.packages()[,"Package"] == FALSE) {
    install.packages("devtools")
}
devtools::install_github("philferriere/mscstexta4r")
```

**Comment by andreaphsz** [comment]
Thank you very much for your answer!
I have installed the developer version and the print operation now works fine. Output is now:

```
textatopics [https://westus.api.cognitive.microsoft.com/text/analytics/v2.0/topics?]
status: Failed
operationId: f9da8cfcfabc4da48a06ef0deb49*
operationType: topics
```

If defined `myTopics`as above I get:

```
> myTopics$json
[1] "{\"status\":\"Failed\",\"createdDateTime\":\"2016-06-22T08:36:48Z\",\"operationType\":\"topics\",\"message\":\"Internal error while executing BES operation.\"}"
```

But as you mentioned, document's language is indeed German...that seems to be the problem!

**Comment by philferriere** [comment]
Thank you for the confirmation, Andrea. 
Version 0.1.2 has been uploaded to CRAN and will soon be available for download.
